New folder (2)/website/views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify, send_file
from flask_login import login_required, current_user
from .models import Bike
from datetime import datetime, timezone
from . import db
import json
import pandas as pd
from io import BytesIO

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method == 'POST':
        bike_number = request.form.get('bike_number')
        bike_type = request.form.get('bike_type')
        bike_location = request.form.get('bike_location')
        needs_maintenance = request.form.get('needs_maintenance') == 'on'

        existing_bike = Bike.query.filter_by(number=bike_number).order_by(Bike.id.desc()).first()
        if existing_bike:
            db.session.delete(existing_bike)
            db.session.commit()

        new_bike = Bike(
            number=bike_number,
            type=bike_type,
            location=bike_location,
            needs_maintenance=needs_maintenance,
            user_id=current_user.id
        )
        try:
            db.session.add(new_bike)
            db.session.commit()
            flash('Bike entry added!', category='success')
        except Exception as e:
            db.session.rollback()
            flash(f'Error adding bike entry: {str(e)}', category='error')
        return redirect(url_for('views.home'))

    bikes = Bike.query.all()  # Fetch all bikes
    return render_template("home.html", user=current_user, bikes=bikes)

@views.route('/inventory')
@login_required
def inventory():
    bikes = Bike.query.all()  # Fetch all bikes
    current_date = datetime.now(timezone.utc).date()
    
    # Create a summary similar to the info page
    bike_summary = {}
    for bike in bikes:
        location = bike.location
        if location not in bike_summary:
            bike_summary[location] = {'total': 0, 'types': {}, 'entered_today': 0, 'not_entered_today': 0, 'bikes': []}
        
        bike_summary[location]['total'] += 1
        bike_summary[location]['bikes'].append(bike)
        
        bike_type = bike.type
        if bike_type not in bike_summary[location]['types']:
            bike_summary[location]['types'][bike_type] = 0
        bike_summary[location]['types'][bike_type] += 1

        if bike.date_entered.date() == current_date:
            bike_summary[location]['entered_today'] += 1
        else:
            bike_summary[location]['not_entered_today'] += 1
    
    return render_template("inventory.html", user=current_user, bike_summary=bike_summary, current_date=current_date)

@views.route('/info')
@login_required
def info():
    bikes = Bike.query.filter(Bike.out_of_commission == False).all()
    current_date = datetime.now(timezone.utc).date()
    
    location_summary = {}
    for bike in bikes:
        location = bike.location
        if location not in location_summary:
            location_summary[location] = {'total': 0, 'types': {}, 'entered_today': 0, 'not_entered_today': 0}
        
        location_summary[location]['total'] += 1
        bike_type = bike.type
        if bike_type not in location_summary[location]['types']:
            location_summary[location]['types'][bike_type] = 0
        location_summary[location]['types'][bike_type] += 1

        if bike.date_entered.date() == current_date:
            location_summary[location]['entered_today'] += 1
        else:
            location_summary[location]['not_entered_today'] += 1
    
    return render_template("info.html", user=current_user, location_summary=location_summary)

@views.route('/delete-bike', methods=['POST'])
@login_required
def delete_bike():
    bike_data = json.loads(request.data)
    bike_id = bike_data.get('bikeId')
    bike = Bike.query.get(bike_id)
    if bike:
        try:
            db.session.delete(bike)
            db.session.commit()
            return jsonify({}), 200
        except Exception as e:
            db.session.rollback()
            return jsonify({'error': f'Error deleting bike: {str(e)}'}), 500
    return jsonify({'error': 'Bike not found or not authorized'}), 404

@views.route('/mark-out-of-commission', methods=['POST'])
@login_required
def mark_out_of_commission():
    bike_data = json.loads(request.data)
    bike_id = bike_data.get('bikeId')
    bike = Bike.query.get(bike_id)
    if bike:
        try:
            bike.out_of_commission = True
            db.session.commit()
            return jsonify({}), 200
        except Exception as e:
            db.session.rollback()
            return jsonify({'error': f'Error updating bike: {str(e)}'}), 500
    return jsonify({'error': 'Bike not found or not authorized'}), 404

@views.route('/export')
@login_required
def export():
    # Fetch the data from the database
    bikes = Bike.query.all()

    # Prepare the data for export
    data = []
    for bike in bikes:
        data.append({
            'Number': bike.number,
            'Type': bike.type,
            'Location': bike.location,
            'Needs Maintenance': 'Yes' if bike.needs_maintenance else 'No',
            'Out of Commission': 'Yes' if bike.out_of_commission else 'No'
        })

    # Create a DataFrame
    df = pd.DataFrame(data)

    # Convert DataFrame to an Excel file
    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Bikes')

    output.seek(0)

    # Send the file as a response
    return send_file(output, download_name="bikes.xlsx", as_attachment=True)

New folder (2)/website/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
  />
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous"
  />
  <style>
    .logout-link {
      color: red !important;
    }
  </style>
  <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbar"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <div class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
        <a class="nav-item nav-link" id="home" href="/">Bike Entry</a>
        <a class="nav-item nav-link" id="inventory" href="/inventory">Manage</a>
        <a class="nav-item nav-link" id="info" href="/info">Report</a>
        {% else %}
        <a class="nav-item nav-link" id="login" href="/login">Login</a>
        <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
        {% endif %}
      </div>
      <div class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <a class="nav-item nav-link logout-link mr-4" id="logout" href="/logout">Logout</a>
        {% endif %}
      </div>
    </div>
  </nav>

  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  {% for category, message in messages %}
  {% if category == 'error' %}
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% else %}
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  {% endif %}
  {% endfor %}
  {% endif %}
  {% endwith %}

  <div class="container">{% block content %} {% endblock %}</div>
  <script
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>
  {% block javascript %} {% endblock %}
</body>
</html>

New folder (2)/website/templates/home.html
{% extends "base.html" %}
{% block title %}Bike Entry{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="background-image" style="background-image: url('https://rare-gallery.com/uploads/posts/5418449-ocean-beach-surf-pastel-coast-blue-minimal-landscape-pink-beach-sand-beach-holiday-sand-beach-life-drone-view-from-above-water-wave-calm-vacation-summer-summer-time-creative-commons-images.jpg'); height: 100vh; background-size: cover; background-position: center; position: absolute; width: 100%; top: 0; left: 0; z-index: -1;"></div>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1 class="text-center">Enter Bikes Here</h1>
            <form method="POST">
                <div class="form-group">
                    <label for="bike_number">Bike Number</label>
                    <input type="text" name="bike_number" id="bike_number" class="form-control" required>
                </div>
                <div class="form-group">
                    <label for="bike_type">Bike Size</label>
                    <select class="form-control" id="bike_type" name="bike_type">
                        <option>Small</option>
                        <option>Medium</option>
                        <option>Large</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="bike_location">Bike Location</label>
                    <select class="form-control" id="bike_location" name="bike_location">
                        <option>Sonesta</option>
                        <option>Retail Yard</option>
                        <option>Palmeto Bluff</option>
                        <option>Westin</option>
                    </select>
                </div>
                <div class="form-group form-check">
                    <input type="checkbox" name="needs_maintenance" id="needs_maintenance" class="form-check-input">
                    <label for="needs_maintenance" class="form-check-label">Needs Maintenance</label>
                </div>
                <div class="text-center" style="margin-top: 10px;">
                    <button type="submit" class="btn btn-primary">Add Bike</button>
                </div>
            </form>
        </div>
    </div>
    <div class="logo-image" style="position: fixed; bottom: 10px; right: 10px;">
        <img src="static/images/logo.png" alt="Logo" style="width: 100px; height: auto;">
    </div>
</div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
    function deleteBike(bikeId) {
        fetch("/delete-bike", {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify({ bikeId: bikeId }),
        })
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            return response.json();
        })
        .then(() => {
            window.location.href = "/";
        })
        .catch(error => {
            console.error('There was a problem with the fetch operation:', error);
        });
    }
</script>
{% endblock %}

New folder (2)/website/templates/info.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous">
    <title>Inventory Info</title>
    <style>
        .location-header {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        .bike-type-row {
            border-top: 1px solid #dee2e6;
        }
        .summary-details {
            font-size: 0.8em;
            color: #6c757d;
        }
        .button-row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 15px;
        }
    </style>
</head>
<body>
<div class="container mt-3">
    <div class="button-row">
        <button class="btn btn-secondary" onclick="history.back()">Back</button>
        <button class="btn btn-primary" onclick="window.print()">Print</button>
    </div>
    <h1>Report</h1>

    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Location</th>
                    <th>Type</th>
                    <th>Count</th>
                </tr>
            </thead>
            <tbody>
                {% for location, summary in location_summary.items() %}
                <tr class="location-header">
                    <td colspan="3">
                        {{ location }} (Total: {{ summary.total }})
                        <div class="summary-details">
                            Entered Today: {{ summary.entered_today }} | Not Entered Today: {{ summary.not_entered_today }}
                        </div>
                    </td>
                </tr>
                {% for bike_type, count in summary.types.items() %}
                <tr class="bike-type-row">
                    <td></td>
                    <td>{{ bike_type }}</td>
                    <td>{{ count }}</td>
                </tr>
                {% endfor %}
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poTiaI6ukYhS5Qb3vTAR5QY9hE7LrH/oBkFhJVbT5jWjUif4Rk" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-pzjw8f+ua7Kw1TIqpgItMu7FtLgQ3uvBTewCk7CuLQ7nuRsSfoT6KR0f1G2Yh9n0" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"></script>
</body>
</html>

New folder (2)/website/templates/inventory.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous">
    <title>Manage</title>
    <style>
        .out-of-commission {
            background-color: #f8d7da;
            color: #721c24;
        }
        .out-of-commission .btn-warning {
            display: none;
        }
        .out-of-commission .btn-danger {
            margin-right: 10px;
        }
        .date-entered-today {
            color: green;
            text-shadow: 0 0 5px rgba(0, 255, 0, 0.5), 0 0 10px rgba(0, 255, 0, 0.4), 0 0 15px rgba(0, 255, 0, 0.3);
        }
        .date-entered-wrong {
            color: red;
            text-shadow: 0 0 5px rgba(255, 0, 0, 0.5), 0 0 10px rgba(255, 0, 0, 0.4), 0 0 15px rgba(255, 0, 0, 0.3);
        }
        .button-row {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 15px;
        }
        .search-result {
            display: flex;
            flex-wrap: wrap;
        }
        .search-result h2 {
            flex-basis: 100%;
        }
        .list-group-item {
            width: 100%;
            margin-bottom: 15px;
        }
        @media (min-width: 768px) {
            .list-group-item {
                flex-basis: calc(50% - 15px);
                margin-right: 15px;
            }
        }
    </style>
</head>
<body>
<div class="container mt-3">
    <div class="button-row">
        <button class="btn btn-secondary" onclick="history.back()">Back</button>
        <a href="{{ url_for('views.export') }}" class="btn btn-success">Export to Excel</a>
    </div>
    <h1>Manage</h1>

    <!-- Search and Filter Bar -->
    <input class="form-control mb-3" id="searchBar" type="text" placeholder="Search by number, type, or location..." onkeyup="searchBikes()">

    <div class="search-result">
        {% for location, summary in bike_summary.items() %}
            <h2>{{ location }}</h2>
            <ul class="list-group list-group-flush">
                {% for bike in summary.bikes %}
                <li class="list-group-item {% if bike.out_of_commission %}out-of-commission{% endif %}">
                    <p>Number: {{ bike.number }}</p>
                    <p>Type: {{ bike.type }}</p>
                    <p>Location: {{ bike.location }}</p>
                    <p>Needs Maintenance: {{ 'Yes' if bike.needs_maintenance else 'No' }}</p>
                    <p>Out of Commission: {{ 'Yes' if bike.out_of_commission else 'No' }}</p>
                    <p class="date-entered {% if bike.date_entered.date() != current_date %}date-entered-wrong{% else %}date-entered-today{% endif %}" data-date="{{ bike.date_entered.date() }}">Date Entered: {{ bike.date_entered.date() }}</p>
                    <button class="btn btn-danger" onclick="deleteBike('{{ bike.id }}')">Delete</button>
                    <button class="btn btn-warning" onclick="markOutOfCommission('{{ bike.id }}')">Mark Out of Commission</button>
                </li>
                {% endfor %}
            </ul>
        {% endfor %}
    </div>
</div>

<script>
    function deleteBike(bikeId) {
        fetch("/delete-bike", {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify({ bikeId: bikeId }),
        })
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            return response.json();
        })
        .then(() => {
            window.location.reload();
        })
        .catch(error => {
            console.error('There was a problem with the fetch operation:', error);
        });
    }

    function markOutOfCommission(bikeId) {
        fetch("/mark-out-of-commission", {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify({ bikeId: bikeId }),
        })
        .then(response => {
            if (!response.ok) {
                throw new Error('Network response was not ok');
            }
            return response.json();
        })
        .then(() => {
            window.location.reload();
        })
        .catch(error => {
            console.error('There was a problem with the fetch operation:', error);
        });
    }

    function searchBikes() {
        const searchBar = document.getElementById('searchBar');
        const filter = searchBar.value.toLowerCase();
        const searchResult = document.querySelector('.search-result');
        const bikeItems = searchResult.getElementsByTagName('li');

        for (let i = 0; i < bikeItems.length; i++) {
            const bikeNumber = bikeItems[i].querySelector('p:nth-of-type(1)').textContent.toLowerCase();
            const bikeType = bikeItems[i].querySelector('p:nth-of-type(2)').textContent.toLowerCase();
            const bikeLocation = bikeItems[i].querySelector('p:nth-of-type(3)').textContent.toLowerCase();
            if (bikeNumber.indexOf(filter) > -1 || bikeType.indexOf(filter) > -1 || bikeLocation.indexOf(filter) > -1) {
                bikeItems[i].style.display = "";
            } else {
                bikeItems[i].style.display = "none";
            }
        }
    }

    document.addEventListener('DOMContentLoaded', (event) => {
        const today = new Date().toISOString().split('T')[0];  // Ensure this is in UTC
        const dateElements = document.querySelectorAll('.date-entered');

        dateElements.forEach(el => {
            const dateEntered = el.dataset.date;
            if (dateEntered === today) {
                el.classList.add('date-entered-today');
                el.classList.remove('date-entered-wrong');
            } else {
                el.classList.add('date-entered-wrong');
                el.classList.remove('date-entered-today');
            }
        });
    });
</script>

</body>
</html>

New folder (2)/website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
<form method="POST">
    <div class="container mt-5">
        <div class="background-image" style="background-image: url('https://img.freepik.com/free-photo/vivid-blurred-colorful-wallpaper-background_58702-3798.jpg'); height: 100vh; background-size: cover; background-position: center; position: absolute; width: 100%; top: 0; left: 0; z-index: -1;"></div>
        <h3 align="center">Login</h3>
        <div class="form-group">
            <label for="email">Email Address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" required>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Enter password" required>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Login</button>
    </div>
</form>
{% endblock %}

New folder (2)/website/templates/sign_up.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}
{% block content %}
<form method="POST">
    <div class="container mt-5">
        <div class="background-image" style="background-image: url('https://img.freepik.com/free-photo/vivid-blurred-colorful-wallpaper-background_58702-3798.jpg'); height: 100vh; background-size: cover; background-position: center; position: absolute; width: 100%; top: 0; left: 0; z-index: -1;"></div>
        <h3 align="center">Sign Up</h3>
        <div class="form-group">
            <label for="email">Email Address</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" required>
        </div>
        <div class="form-group">
            <label for="firstName">First Name</label>
            <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter first name" required>
        </div>
        <div class="form-group">
            <label for="password1">Password</label>
            <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password" required>
        </div>
        <div class="form-group">
            <label for="password2">Password (Confirm)</label>
            <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password" required>
        </div>
        <div class="form-group">
            <label for="secretCode">Admin Code</label>
            <input type="text" class="form-control" id="secretCode" name="secretCode" placeholder="Enter admin code" required>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    </div>
{% endblock %}